version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9  # Use the same Python version as AWS Lambda
    commands:
      - echo "Installing dependencies..."
      - pip install --upgrade pip
      - pip install pycryptodome -t package/
      - pip install pandas python-binance -t package/

  build:
    commands:
      - echo "Packaging Lambda function..."
      - cp ./lambda_package/lambda_function.py package/
      - cp ./lambda_package/binance_trade_wrapper.py package/
      - cd package
      - rm -rf */tests */test *.dist-info/RECORD
      - zip -r ../lambda_function.zip .
      - cd ..

  post_build:
    commands:
      - echo "Checking if ZIP file exists..."
      - ls -lah lambda_function.zip  # List files to debug
      - echo "Uploading to AWS Lambda..."
      - aws lambda update-function-code --function-name TradingViewWebhookProcessorV1 --zip-file fileb://lambda_function.zip

artifacts:
  files:
    - lambda_function.zip
