version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
  build:
    commands:
      - echo "Packaging Lambda function..."
      - cd lambda_package
      - find . -name "*.pyc" -delete
      - find . -name "__pycache__" -type d -exec rm -r {} +
      - zip -r ../lambda_function.zip .
      - cd ..

  post_build:
    commands:
      - echo "Checking ZIP file size..."
      - ls -lah lambda_function.zip
      - echo "Uploading to S3..."
      - aws s3 cp lambda_function.zip s3://nnln-lambda-deployment/lambda_function.zip
      - echo "Updating Lambda function from S3..."
      - aws lambda update-function-code --function-name TradingViewWebhookProcessorV1 --s3-bucket nnln-lambda-deployment --s3-key lambda_function.zip

artifacts:
  files:
    - lambda_function.zip