version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9  # Use the same Python version as AWS Lambda
    commands:
      - echo "Installing dependencies..."
      - pip install --upgrade pip
      - pip install pycryptodome -t package/
      - pip install pandas python-binance -t package/

  build:
    commands:
      - echo "Packaging Lambda function..."
      - cp ./lambda_package/lambda_function.py package/
      - cp ./lambda_package/binance_trade_wrapper.py package/
      - cd package
      - rm -rf */tests */test *.dist-info/RECORD
      - zip -r ../lambda_function.zip .
      - cd ..

  post_build:
    commands:
      - echo "Checking ZIP file size..."
      - ls -lah lambda_function.zip  # Debug: Check size
      - echo "Uploading to S3..."
      - aws s3 cp lambda_function.zip s3://nnln-lambda-deployment/lambda_function.zip  # Correct S3 bucket name
      - echo "Updating Lambda function from S3..."
      - aws lambda update-function-code --function-name TradingViewWebhookProcessorV1 --s3-bucket nnln-lambda-deployment --s3-key lambda_function.zip  # Corrected option

artifacts:
  files:
    - lambda_function.zip
